permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author:
  name: Yeung Ben
  email: yeungben@163.com
  link: http://blog.youngben.net
  weibo: http://weibo.com/GeekBen
  github: http://github.com/yeungben
  music: http://douban.fm/
  linkedin: https://cn.linkedin.com/in/geekben

# 站点信息
title: Ben's Blog
description: My personal blog
url: http://blog.youngben.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/Me.png
favicon: /public/img/ben.png

# google analytics 设置
ga:
  id: UA-61303211-1
  url: blog.youngben.net

# disqus 设置
disqus:
  shortname: yeungben

# 站内搜索:
# 微搜索:/pages/search.html

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates:
  - Optimization
  - Git

# qiniu CDN
# safe: false
# cdn_url : https://dn-yeungben.qbox.me

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
