markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.youngeben.net
title: Ben's Blog
description: Linux,TCP/IP,Pythhon reading...
author: Yeung Ben
email: yeungben@163.com
github: yeungben

config:
  js_dir:
  img_dir:
  css_dir:
